// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AdvancedMobileDeviceSearchCriteria struct {
	Criterion *Criterion `json:"criterion,omitempty"`
	Size      *int64     `json:"size,omitempty"`
}

type AdvancedMobileDeviceSearchDisplayFieldsDisplayField struct {
	// Name of the display field
	Name *string `json:"name,omitempty"`
}

type AdvancedMobileDeviceSearchDisplayFields struct {
	DisplayField *AdvancedMobileDeviceSearchDisplayFieldsDisplayField `json:"display_field,omitempty"`
	Size         *int64                                               `json:"size,omitempty"`
}

type AdvancedMobileDeviceSearchMobileDevicesMobileDevice struct {
	DisplayName *string `json:"Display_Name,omitempty"`
	ID          *int64  `json:"id,omitempty"`
	// Name of the mobile device
	Name *string `json:"name,omitempty"`
	Udid *string `json:"udid,omitempty"`
}

type AdvancedMobileDeviceSearchMobileDevices struct {
	MobileDevice *AdvancedMobileDeviceSearchMobileDevicesMobileDevice `json:"mobile_device,omitempty"`
	Size         *int64                                               `json:"size,omitempty"`
}

// AdvancedMobileDeviceSearch - OK
type AdvancedMobileDeviceSearch struct {
	Criteria      []AdvancedMobileDeviceSearchCriteria      `json:"criteria,omitempty"`
	DisplayFields []AdvancedMobileDeviceSearchDisplayFields `json:"display_fields,omitempty"`
	ID            *int64                                    `json:"id,omitempty"`
	MobileDevices []AdvancedMobileDeviceSearchMobileDevices `json:"mobile_devices,omitempty"`
	// Name of the advanced mobile device search
	Name   string      `json:"name"`
	Site   *SiteObject `json:"site,omitempty"`
	Sort1  *string     `json:"sort_1,omitempty"`
	Sort2  *string     `json:"sort_2,omitempty"`
	Sort3  *string     `json:"sort_3,omitempty"`
	ViewAs *string     `json:"view_as,omitempty"`
}
