// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AdvancedComputerSearchComputersComputer struct {
	ComputerName *string `json:"Computer_Name,omitempty"`
	ID           *int64  `json:"id,omitempty"`
	// Name of the computer
	Name *string `json:"name,omitempty"`
	Udid *string `json:"udid,omitempty"`
}

type AdvancedComputerSearchComputers struct {
	Computer *AdvancedComputerSearchComputersComputer `json:"computer,omitempty"`
	Size     *int64                                   `json:"size,omitempty"`
}

type AdvancedComputerSearchCriteria struct {
	Criterion *Criterion `json:"criterion,omitempty"`
	Size      *int64     `json:"size,omitempty"`
}

type AdvancedComputerSearchDisplayFieldsDisplayField struct {
	// Name of the display field
	Name *string `json:"name,omitempty"`
}

type AdvancedComputerSearchDisplayFields struct {
	DisplayField *AdvancedComputerSearchDisplayFieldsDisplayField `json:"display_field,omitempty"`
	Size         *int64                                           `json:"size,omitempty"`
}

// AdvancedComputerSearch - OK
type AdvancedComputerSearch struct {
	Computers     []AdvancedComputerSearchComputers     `json:"computers,omitempty"`
	Criteria      []AdvancedComputerSearchCriteria      `json:"criteria,omitempty"`
	DisplayFields []AdvancedComputerSearchDisplayFields `json:"display_fields,omitempty"`
	ID            *int64                                `json:"id,omitempty"`
	// Name of the advanced computer search
	Name   string      `json:"name"`
	Site   *SiteObject `json:"site,omitempty"`
	Sort1  *string     `json:"sort_1,omitempty"`
	Sort2  *string     `json:"sort_2,omitempty"`
	Sort3  *string     `json:"sort_3,omitempty"`
	ViewAs *string     `json:"view_as,omitempty"`
}
