// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Computers struct {
	Computer *IDName `json:"computer,omitempty"`
	Size     *int64  `json:"size,omitempty"`
}
