// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DirectoryBinding - OK
type DirectoryBinding struct {
	// OU to bind computers to
	ComputerOu *string `json:"computer_ou,omitempty"`
	Domain     *string `json:"domain,omitempty"`
	ID         *int64  `json:"id,omitempty"`
	// Name of the binding
	Name string `json:"name"`
	// Password for the network administrator account
	Password *string `json:"password,omitempty"`
	Priority *int64  `json:"priority,omitempty"`
	Type     *string `json:"type,omitempty"`
	// Network administrator account to bind with
	Username *string `json:"username,omitempty"`
}
