// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DockItems struct {
	DockItem *IDName `json:"dock_item,omitempty"`
	Size     *int64  `json:"size,omitempty"`
}
