// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// InfrastructureManager - OK
type InfrastructureManager struct {
	Hostname                  *string `json:"hostname,omitempty"`
	ID                        *int64  `json:"id,omitempty"`
	LastCheckIn               *string `json:"last_check_in,omitempty"`
	LastReportedIP            *string `json:"last_reported_ip,omitempty"`
	Name                      *string `json:"name,omitempty"`
	OperatingSystem           *string `json:"operating_system,omitempty"`
	OperatingSystemVersion    *string `json:"operating_system_version,omitempty"`
	RecurringCheckInFrequency *int64  `json:"recurring_check_in_frequency,omitempty"`
	UUID                      *string `json:"uuid,omitempty"`
}
