// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JSONWebTokenConfigurations struct {
	JSONWebTokenConfiguration *JSONWebTokenConfiguration `json:"json_web_token_configuration,omitempty"`
}
