// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MobileDeviceApplicationsApplication struct {
	ApplicationName    *string `json:"application_name,omitempty"`
	ApplicationVersion *string `json:"application_version,omitempty"`
	Identifier         *string `json:"identifier,omitempty"`
}

type MobileDeviceApplications1 struct {
	Application *MobileDeviceApplicationsApplication `json:"application,omitempty"`
	Size        *int64                               `json:"size,omitempty"`
}

type MobileDeviceCertificatesCertificate struct {
	CommonName *string `json:"common_name,omitempty"`
	Identity   *bool   `json:"identity,omitempty"`
}

type MobileDeviceCertificates struct {
	Certificate *MobileDeviceCertificatesCertificate `json:"certificate,omitempty"`
	Size        *int64                               `json:"size,omitempty"`
}

type MobileDeviceConfigurationProfilesConfigurationProfile1 struct {
	DisplayName *string `json:"display_name,omitempty"`
	Identifier  *string `json:"identifier,omitempty"`
	UUID        *string `json:"uuid,omitempty"`
	Version     *int64  `json:"version,omitempty"`
}

type MobileDeviceConfigurationProfiles1 struct {
	ConfigurationProfile *MobileDeviceConfigurationProfilesConfigurationProfile1 `json:"configuration_profile,omitempty"`
	Size                 *int64                                                  `json:"size,omitempty"`
}

type MobileDeviceExtensionAttributes1 struct {
	ID    *int64  `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type MobileDeviceGeneral struct {
	AssetTag                           *string `json:"asset_tag,omitempty"`
	Available                          *int64  `json:"available,omitempty"`
	AvailableMb                        *int64  `json:"available_mb,omitempty"`
	BatteryLevel                       *int64  `json:"battery_level,omitempty"`
	BleCapable                         *bool   `json:"ble_capable,omitempty"`
	BluetoothMacAddress                *string `json:"bluetooth_mac_address,omitempty"`
	Capacity                           *int64  `json:"capacity,omitempty"`
	CapacityMb                         *int64  `json:"capacity_mb,omitempty"`
	CloudBackupEnabled                 *bool   `json:"cloud_backup_enabled,omitempty"`
	DeviceLocatorServiceEnabled        *bool   `json:"device_locator_service_enabled,omitempty"`
	DeviceName                         *string `json:"device_name,omitempty"`
	DeviceOwnershipLevel               *string `json:"device_ownership_level,omitempty"`
	DisplayName                        *string `json:"display_name,omitempty"`
	DoNotDisturbEnabled                *bool   `json:"do_not_disturb_enabled,omitempty"`
	ExchangeActivesyncDeviceIdentifier *string `json:"exchange_activesync_device_identifier,omitempty"`
	ID                                 *int64  `json:"id,omitempty"`
	InitialEntryDateEpoch              *int64  `json:"initial_entry_date_epoch,omitempty"`
	InitialEntryDateUtc                *string `json:"initial_entry_date_utc,omitempty"`
	IPAddress                          *string `json:"ip_address,omitempty"`
	ItunesStoreAccountIsActive         *bool   `json:"itunes_store_account_is_active,omitempty"`
	LastBackupTimeEpoch                *int64  `json:"last_backup_time_epoch,omitempty"`
	LastBackupTimeUtc                  *string `json:"last_backup_time_utc,omitempty"`
	LastCloudBackupDateEpoch           *int64  `json:"last_cloud_backup_date_epoch,omitempty"`
	LastCloudBackupDateUtc             *string `json:"last_cloud_backup_date_utc,omitempty"`
	LastEnrollmentEpoch                *int64  `json:"last_enrollment_epoch,omitempty"`
	LastEnrollmentUtc                  *string `json:"last_enrollment_utc,omitempty"`
	LastInventoryUpdate                *string `json:"last_inventory_update,omitempty"`
	LastInventoryUpdateEpoch           *int64  `json:"last_inventory_update_epoch,omitempty"`
	LastInventoryUpdateUtc             *string `json:"last_inventory_update_utc,omitempty"`
	LocationServicesEnabled            *bool   `json:"location_services_enabled,omitempty"`
	Managed                            *bool   `json:"managed,omitempty"`
	Model                              *string `json:"model,omitempty"`
	ModelDisplay                       *string `json:"model_display,omitempty"`
	ModelIdentifier                    *string `json:"model_identifier,omitempty"`
	ModelNumber                        *string `json:"model_number,omitempty"`
	ModemFirmware                      *string `json:"modem_firmware,omitempty"`
	Name                               string  `json:"name"`
	OsBuild                            *string `json:"os_build,omitempty"`
	OsType                             *string `json:"os_type,omitempty"`
	OsVersion                          *string `json:"os_version,omitempty"`
	PercentageUsed                     *int64  `json:"percentage_used,omitempty"`
	PhoneNumber                        *string `json:"phone_number,omitempty"`
	SerialNumber                       string  `json:"serial_number"`
	Shared                             *string `json:"shared,omitempty"`
	Supervised                         *bool   `json:"supervised,omitempty"`
	Tethered                           *string `json:"tethered,omitempty"`
	Udid                               string  `json:"udid"`
	WifiMacAddress                     *string `json:"wifi_mac_address,omitempty"`
}

type MobileDeviceMobileDeviceGroups struct {
	MobileDeviceGroup *IDName `json:"mobile_device_group,omitempty"`
	Size              *int64  `json:"size,omitempty"`
}

type MobileDeviceNetwork struct {
	CarrierSettingsVersion   *string `json:"carrier_settings_version,omitempty"`
	CellularTechnology       *string `json:"cellular_technology,omitempty"`
	CurrentCarrierNetwork    *string `json:"current_carrier_network,omitempty"`
	CurrentMobileCountryCode *string `json:"current_mobile_country_code,omitempty"`
	CurrentMobileNetworkCode *string `json:"current_mobile_network_code,omitempty"`
	DataRoamingEnabled       *bool   `json:"data_roaming_enabled,omitempty"`
	HomeCarrierNetwork       *string `json:"home_carrier_network,omitempty"`
	HomeMobileCountryCode    *string `json:"home_mobile_country_code,omitempty"`
	HomeMobileNetworkCode    *string `json:"home_mobile_network_code,omitempty"`
	Iccid                    *string `json:"iccid,omitempty"`
	Imei                     *string `json:"imei,omitempty"`
	PhoneNumber              *string `json:"phone_number,omitempty"`
	VoiceRoamingEnabled      *string `json:"voice_roaming_enabled,omitempty"`
}

type MobileDeviceProvisioningProfilesMobileDeviceProvisioningProfile1 struct {
	DisplayName         *string `json:"display_name,omitempty"`
	ExpirationDate      *string `json:"expiration_date,omitempty"`
	ExpirationDateEpoch *int64  `json:"expiration_date_epoch,omitempty"`
	ExpirationDateUtc   *string `json:"expiration_date_utc,omitempty"`
	UUID                *string `json:"uuid,omitempty"`
}

type MobileDeviceProvisioningProfiles1 struct {
	MobileDeviceProvisioningProfile *MobileDeviceProvisioningProfilesMobileDeviceProvisioningProfile1 `json:"mobile_device_provisioning_profile,omitempty"`
	Size                            *int64                                                            `json:"size,omitempty"`
}

type MobileDeviceSecurityObject struct {
	ActivationLockEnabled           *bool   `json:"activation_lock_enabled,omitempty"`
	BlockLevelEncryptionCapable     *bool   `json:"block_level_encryption_capable,omitempty"`
	DataProtection                  *bool   `json:"data_protection,omitempty"`
	FileLevelEncryptionCapable      *bool   `json:"file_level_encryption_capable,omitempty"`
	HardwareEncryption              *string `json:"hardware_encryption,omitempty"`
	JailbreakDetected               *string `json:"jailbreak_detected,omitempty"`
	LostLocationAltitude            *string `json:"lost_location_altitude,omitempty"`
	LostLocationCourse              *string `json:"lost_location_course,omitempty"`
	LostLocationEpoch               *int64  `json:"lost_location_epoch,omitempty"`
	LostLocationHorizontalAccuracy  *string `json:"lost_location_horizontal_accuracy,omitempty"`
	LostLocationLatitude            *string `json:"lost_location_latitude,omitempty"`
	LostLocationLongitude           *string `json:"lost_location_longitude,omitempty"`
	LostLocationSpeed               *string `json:"lost_location_speed,omitempty"`
	LostLocationUtc                 *string `json:"lost_location_utc,omitempty"`
	LostLocationVerticalAccuracy    *string `json:"lost_location_vertical_accuracy,omitempty"`
	LostModeEnableIssuedEpoch       *int64  `json:"lost_mode_enable_issued_epoch,omitempty"`
	LostModeEnableIssuedUtc         *string `json:"lost_mode_enable_issued_utc,omitempty"`
	LostModeEnabled                 *string `json:"lost_mode_enabled,omitempty"`
	LostModeEnforced                *bool   `json:"lost_mode_enforced,omitempty"`
	LostModeFootnote                *string `json:"lost_mode_footnote,omitempty"`
	LostModeMessage                 *string `json:"lost_mode_message,omitempty"`
	LostModePhone                   *string `json:"lost_mode_phone,omitempty"`
	PasscodeCompliant               *bool   `json:"passcode_compliant,omitempty"`
	PasscodeCompliantWithProfile    *bool   `json:"passcode_compliant_with_profile,omitempty"`
	PasscodeLockGracePeriodEnforced *string `json:"passcode_lock_grace_period_enforced,omitempty"`
	PasscodePresent                 *bool   `json:"passcode_present,omitempty"`
}

// MobileDevice - OK
type MobileDevice struct {
	Applications          []MobileDeviceApplications1          `json:"applications,omitempty"`
	Certificates          []MobileDeviceCertificates           `json:"certificates,omitempty"`
	ConfigurationProfiles []MobileDeviceConfigurationProfiles1 `json:"configuration_profiles,omitempty"`
	ExtensionAttributes   []MobileDeviceExtensionAttributes1   `json:"extension_attributes,omitempty"`
	General               *MobileDeviceGeneral                 `json:"general,omitempty"`
	Location              *Location                            `json:"location,omitempty"`
	MobileDeviceGroups    []MobileDeviceMobileDeviceGroups     `json:"mobile_device_groups,omitempty"`
	Network               *MobileDeviceNetwork                 `json:"network,omitempty"`
	ProvisioningProfiles  []MobileDeviceProvisioningProfiles1  `json:"provisioning_profiles,omitempty"`
	Purchasing            *Purchasing                          `json:"purchasing,omitempty"`
	SecurityObject        *MobileDeviceSecurityObject          `json:"security_object,omitempty"`
}
