// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NetworkSegment - OK
type NetworkSegment struct {
	Building           *string `json:"building,omitempty"`
	Department         *string `json:"department,omitempty"`
	DistributionPoint  *string `json:"distribution_point,omitempty"`
	DistributionServer *string `json:"distribution_server,omitempty"`
	EndingAddress      string  `json:"ending_address"`
	ID                 *int64  `json:"id,omitempty"`
	// Name of the network segment
	Name                string  `json:"name"`
	OverrideBuildings   *bool   `json:"override_buildings,omitempty"`
	OverrideDepartments *bool   `json:"override_departments,omitempty"`
	StartingAddress     string  `json:"starting_address"`
	SwuServer           *string `json:"swu_server,omitempty"`
	URL                 *string `json:"url,omitempty"`
}
