// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// CreateLogFlushForIntervalLog - At this time, only 'policy' logs are supported
type CreateLogFlushForIntervalLog string

const (
	CreateLogFlushForIntervalLogPolicy CreateLogFlushForIntervalLog = "policy"
)

func (e CreateLogFlushForIntervalLog) ToPointer() *CreateLogFlushForIntervalLog {
	return &e
}

func (e *CreateLogFlushForIntervalLog) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "policy":
		*e = CreateLogFlushForIntervalLog(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateLogFlushForIntervalLog: %v", v)
	}
}

type CreateLogFlushForIntervalRequest struct {
	// Supported values are a combination of [Zero, One, Two, Three, Six] and [Days, Weeks, Months, Years]. For example, JSSResource/logflush/policies/interval/Three+Months
	Interval string `pathParam:"style=simple,explode=false,name=interval"`
	// At this time, only 'policy' logs are supported
	Log CreateLogFlushForIntervalLog `pathParam:"style=simple,explode=false,name=log"`
}

type CreateLogFlushForIntervalResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
