// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreatePatchSoftwareTitlesByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type CreatePatchSoftwareTitlesByIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
