// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreatePatchPolicyBySoftwareTitleConfigIDRequest struct {
	// Patch software title config ID value to filter by
	Softwaretitleconfigid int64 `pathParam:"style=simple,explode=false,name=softwaretitleconfigid"`
}

type CreatePatchPolicyBySoftwareTitleConfigIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
