// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAllowedFileExtensionByIDRequest struct {
	// Database ID of the extension
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteAllowedFileExtensionByIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
