// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"jamf/internal/sdk/pkg/models/shared"
	"jamf/internal/sdk/pkg/types"
	"net/http"
)

// FindComputerHardwareSoftwareReportsBySerialSubsetSubset - Subset to filter by
type FindComputerHardwareSoftwareReportsBySerialSubsetSubset string

const (
	FindComputerHardwareSoftwareReportsBySerialSubsetSubsetSoftware FindComputerHardwareSoftwareReportsBySerialSubsetSubset = "Software"
	FindComputerHardwareSoftwareReportsBySerialSubsetSubsetHardwre  FindComputerHardwareSoftwareReportsBySerialSubsetSubset = "Hardwre"
	FindComputerHardwareSoftwareReportsBySerialSubsetSubsetFonts    FindComputerHardwareSoftwareReportsBySerialSubsetSubset = "Fonts"
	FindComputerHardwareSoftwareReportsBySerialSubsetSubsetPlugins  FindComputerHardwareSoftwareReportsBySerialSubsetSubset = "Plugins"
)

func (e FindComputerHardwareSoftwareReportsBySerialSubsetSubset) ToPointer() *FindComputerHardwareSoftwareReportsBySerialSubsetSubset {
	return &e
}

func (e *FindComputerHardwareSoftwareReportsBySerialSubsetSubset) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Software":
		fallthrough
	case "Hardwre":
		fallthrough
	case "Fonts":
		fallthrough
	case "Plugins":
		*e = FindComputerHardwareSoftwareReportsBySerialSubsetSubset(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindComputerHardwareSoftwareReportsBySerialSubsetSubset: %v", v)
	}
}

type FindComputerHardwareSoftwareReportsBySerialSubsetRequest struct {
	// End date (e.g. yyyy-mm-dd)
	EndDate types.Date `pathParam:"style=simple,explode=false,name=end_date"`
	// Serial number to filter by
	Serialnumber string `pathParam:"style=simple,explode=false,name=serialnumber"`
	// Start date (e.g. yyyy-mm-dd)
	StartDate types.Date `pathParam:"style=simple,explode=false,name=start_date"`
	// Subset to filter by
	Subset FindComputerHardwareSoftwareReportsBySerialSubsetSubset `pathParam:"style=simple,explode=false,name=subset"`
}

type FindComputerHardwareSoftwareReportsBySerialSubsetResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ComputerHardwareSoftwareReports *shared.ComputerHardwareSoftwareReports
}
