// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FindComputerHistoryByNameRequest struct {
	// Computer Name to filter by
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

type FindComputerHistoryByName200ApplicationXMLAuditsAudit struct {
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	Event         *string
	Username      *string
}

type FindComputerHistoryByName200ApplicationXMLAudits struct {
	Audit *FindComputerHistoryByName200ApplicationXMLAuditsAudit
}

type FindComputerHistoryByName200ApplicationXMLCasperImagingLogsCasperImagingLog struct {
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	Status        *string
}

type FindComputerHistoryByName200ApplicationXMLCasperImagingLogs struct {
	CasperImagingLog *FindComputerHistoryByName200ApplicationXMLCasperImagingLogsCasperImagingLog
}

type FindComputerHistoryByName200ApplicationXMLCasperRemoteLogsCasperRemoteLog struct {
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	Status        *string
}

type FindComputerHistoryByName200ApplicationXMLCasperRemoteLogs struct {
	CasperRemoteLog *FindComputerHistoryByName200ApplicationXMLCasperRemoteLogsCasperRemoteLog
}

type FindComputerHistoryByName200ApplicationXMLCommandsCompletedCommand struct {
	Completed      *string
	CompletedEpoch *string
	CompletedUtc   *string
	Name           *string
	Username       *string
}

type FindComputerHistoryByName200ApplicationXMLCommandsCompleted struct {
	Command *FindComputerHistoryByName200ApplicationXMLCommandsCompletedCommand
}

type FindComputerHistoryByName200ApplicationXMLCommandsFailedCommand struct {
	Failed      *string
	FailedEpoch *string
	FailedUtc   *string
	Issued      *string
	IssuedEpoch *string
	IssuedUtc   *string
	Name        *string
	Status      *string
}

type FindComputerHistoryByName200ApplicationXMLCommandsFailed struct {
	Command *FindComputerHistoryByName200ApplicationXMLCommandsFailedCommand
}

type FindComputerHistoryByName200ApplicationXMLCommandsPendingCommand struct {
	Issued        *string
	IssuedEpoch   *string
	IssuedUtc     *string
	LastPush      *string
	LastPushEpoch *string
	LastPushUtc   *string
	Name          *string
	Status        *string
	Username      *string
}

type FindComputerHistoryByName200ApplicationXMLCommandsPending struct {
	Command *FindComputerHistoryByName200ApplicationXMLCommandsPendingCommand
}

type FindComputerHistoryByName200ApplicationXMLCommands struct {
	Completed []FindComputerHistoryByName200ApplicationXMLCommandsCompleted
	Failed    []FindComputerHistoryByName200ApplicationXMLCommandsFailed
	Pending   []FindComputerHistoryByName200ApplicationXMLCommandsPending
}

type FindComputerHistoryByName200ApplicationXMLComputerUsageLogsUsageLog struct {
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	Event         *string
	Username      *string
}

type FindComputerHistoryByName200ApplicationXMLComputerUsageLogs struct {
	UsageLog *FindComputerHistoryByName200ApplicationXMLComputerUsageLogsUsageLog
}

type FindComputerHistoryByName200ApplicationXMLGeneral struct {
	ID         *int64
	MacAddress *string
	// Name of the computer
	Name         *string
	SerialNumber *string
	Udid         *string
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsFailedApp struct {
	Deployed        *string
	DeployedEpoch   *int64
	DeployedUtc     *string
	LastUpdate      *string
	LastUpdateEpoch *int64
	LastUpdateUtc   *string
	Name            *string
	Status          *string
	Version         *string
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsFailed struct {
	App *FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsFailedApp
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsInstalledApp struct {
	Name    *string
	SizeMb  *string
	Version *string
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsInstalled struct {
	App *FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsInstalledApp
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsPendingApp struct {
	Deployed        *string
	DeployedEpoch   *int64
	DeployedUtc     *string
	LastUpdate      *string
	LastUpdateEpoch *int64
	LastUpdateUtc   *string
	Name            *string
	Version         *string
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsPending struct {
	App *FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsPendingApp
}

type FindComputerHistoryByName200ApplicationXMLMacAppStoreApplications struct {
	Failed    []FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsFailed
	Installed []FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsInstalled
	Pending   []FindComputerHistoryByName200ApplicationXMLMacAppStoreApplicationsPending
}

type FindComputerHistoryByName200ApplicationXMLPolicyLogsPolicyLog struct {
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	PolicyID      *int64
	PolicyName    *string
	Status        *string
	Username      *string
}

type FindComputerHistoryByName200ApplicationXMLPolicyLogs struct {
	PolicyLog *FindComputerHistoryByName200ApplicationXMLPolicyLogsPolicyLog
}

type FindComputerHistoryByName200ApplicationXMLScreenSharingLogsScreenSharingLog struct {
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	Details       *string
	Status        *string
}

type FindComputerHistoryByName200ApplicationXMLScreenSharingLogs struct {
	ScreenSharingLog *FindComputerHistoryByName200ApplicationXMLScreenSharingLogsScreenSharingLog
}

type FindComputerHistoryByName200ApplicationXMLUserLocationLocation struct {
	Building      *string
	DateTime      *string
	DateTimeEpoch *string
	DateTimeUtc   *string
	Department    *string
	EmailAddress  *string
	FullName      *string
	PhoneNumber   *string
	Position      *string
	Room          *string
	Username      *string
}

type FindComputerHistoryByName200ApplicationXMLUserLocation struct {
	Location *FindComputerHistoryByName200ApplicationXMLUserLocationLocation
}

// FindComputerHistoryByName200ApplicationXML - OK
type FindComputerHistoryByName200ApplicationXML struct {
	Audits                  []FindComputerHistoryByName200ApplicationXMLAudits
	CasperImagingLogs       []FindComputerHistoryByName200ApplicationXMLCasperImagingLogs
	CasperRemoteLogs        []FindComputerHistoryByName200ApplicationXMLCasperRemoteLogs
	Commands                *FindComputerHistoryByName200ApplicationXMLCommands
	ComputerUsageLogs       []FindComputerHistoryByName200ApplicationXMLComputerUsageLogs
	General                 *FindComputerHistoryByName200ApplicationXMLGeneral
	MacAppStoreApplications *FindComputerHistoryByName200ApplicationXMLMacAppStoreApplications
	PolicyLogs              []FindComputerHistoryByName200ApplicationXMLPolicyLogs
	ScreenSharingLogs       []FindComputerHistoryByName200ApplicationXMLScreenSharingLogs
	UserLocation            []FindComputerHistoryByName200ApplicationXMLUserLocation
}

type FindComputerHistoryByName200ApplicationJSONAuditsAudit struct {
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	Event         *string `json:"event,omitempty"`
	Username      *string `json:"username,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONAudits struct {
	Audit *FindComputerHistoryByName200ApplicationJSONAuditsAudit `json:"audit,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCasperImagingLogsCasperImagingLog struct {
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	Status        *string `json:"status,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCasperImagingLogs struct {
	CasperImagingLog *FindComputerHistoryByName200ApplicationJSONCasperImagingLogsCasperImagingLog `json:"casper_imaging_log,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCasperRemoteLogsCasperRemoteLog struct {
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	Status        *string `json:"status,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCasperRemoteLogs struct {
	CasperRemoteLog *FindComputerHistoryByName200ApplicationJSONCasperRemoteLogsCasperRemoteLog `json:"casper_remote_log,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommandsCompletedCommand struct {
	Completed      *string `json:"completed,omitempty"`
	CompletedEpoch *string `json:"completed_epoch,omitempty"`
	CompletedUtc   *string `json:"completed_utc,omitempty"`
	Name           *string `json:"name,omitempty"`
	Username       *string `json:"username,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommandsCompleted struct {
	Command *FindComputerHistoryByName200ApplicationJSONCommandsCompletedCommand `json:"command,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommandsFailedCommand struct {
	Failed      *string `json:"failed,omitempty"`
	FailedEpoch *string `json:"failed_epoch,omitempty"`
	FailedUtc   *string `json:"failed_utc,omitempty"`
	Issued      *string `json:"issued,omitempty"`
	IssuedEpoch *string `json:"issued_epoch,omitempty"`
	IssuedUtc   *string `json:"issued_utc,omitempty"`
	Name        *string `json:"name,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommandsFailed struct {
	Command *FindComputerHistoryByName200ApplicationJSONCommandsFailedCommand `json:"command,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommandsPendingCommand struct {
	Issued        *string `json:"issued,omitempty"`
	IssuedEpoch   *string `json:"issued_epoch,omitempty"`
	IssuedUtc     *string `json:"issued_utc,omitempty"`
	LastPush      *string `json:"last_push,omitempty"`
	LastPushEpoch *string `json:"last_push_epoch,omitempty"`
	LastPushUtc   *string `json:"last_push_utc,omitempty"`
	Name          *string `json:"name,omitempty"`
	Status        *string `json:"status,omitempty"`
	Username      *string `json:"username,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommandsPending struct {
	Command *FindComputerHistoryByName200ApplicationJSONCommandsPendingCommand `json:"command,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONCommands struct {
	Completed []FindComputerHistoryByName200ApplicationJSONCommandsCompleted `json:"completed,omitempty"`
	Failed    []FindComputerHistoryByName200ApplicationJSONCommandsFailed    `json:"failed,omitempty"`
	Pending   []FindComputerHistoryByName200ApplicationJSONCommandsPending   `json:"pending,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONComputerUsageLogsUsageLog struct {
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	Event         *string `json:"event,omitempty"`
	Username      *string `json:"username,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONComputerUsageLogs struct {
	UsageLog *FindComputerHistoryByName200ApplicationJSONComputerUsageLogsUsageLog `json:"usage_log,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONGeneral struct {
	ID         *int64  `json:"id,omitempty"`
	MacAddress *string `json:"mac_address,omitempty"`
	// Name of the computer
	Name         *string `json:"name,omitempty"`
	SerialNumber *string `json:"serial_number,omitempty"`
	Udid         *string `json:"udid,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsFailedApp struct {
	Deployed        *string `json:"deployed,omitempty"`
	DeployedEpoch   *int64  `json:"deployed_epoch,omitempty"`
	DeployedUtc     *string `json:"deployed_utc,omitempty"`
	LastUpdate      *string `json:"last_update,omitempty"`
	LastUpdateEpoch *int64  `json:"last_update_epoch,omitempty"`
	LastUpdateUtc   *string `json:"last_update_utc,omitempty"`
	Name            *string `json:"name,omitempty"`
	Status          *string `json:"status,omitempty"`
	Version         *string `json:"version,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsFailed struct {
	App *FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsFailedApp `json:"app,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsInstalledApp struct {
	Name    *string `json:"name,omitempty"`
	SizeMb  *string `json:"size_mb,omitempty"`
	Version *string `json:"version,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsInstalled struct {
	App *FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsInstalledApp `json:"app,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsPendingApp struct {
	Deployed        *string `json:"deployed,omitempty"`
	DeployedEpoch   *int64  `json:"deployed_epoch,omitempty"`
	DeployedUtc     *string `json:"deployed_utc,omitempty"`
	LastUpdate      *string `json:"last_update,omitempty"`
	LastUpdateEpoch *int64  `json:"last_update_epoch,omitempty"`
	LastUpdateUtc   *string `json:"last_update_utc,omitempty"`
	Name            *string `json:"name,omitempty"`
	Version         *string `json:"version,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsPending struct {
	App *FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsPendingApp `json:"app,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONMacAppStoreApplications struct {
	Failed    []FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsFailed    `json:"failed,omitempty"`
	Installed []FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsInstalled `json:"installed,omitempty"`
	Pending   []FindComputerHistoryByName200ApplicationJSONMacAppStoreApplicationsPending   `json:"pending,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONPolicyLogsPolicyLog struct {
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	PolicyID      *int64  `json:"policy_id,omitempty"`
	PolicyName    *string `json:"policy_name,omitempty"`
	Status        *string `json:"status,omitempty"`
	Username      *string `json:"username,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONPolicyLogs struct {
	PolicyLog *FindComputerHistoryByName200ApplicationJSONPolicyLogsPolicyLog `json:"policy_log,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONScreenSharingLogsScreenSharingLog struct {
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	Details       *string `json:"details,omitempty"`
	Status        *string `json:"status,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONScreenSharingLogs struct {
	ScreenSharingLog *FindComputerHistoryByName200ApplicationJSONScreenSharingLogsScreenSharingLog `json:"screen_sharing_log,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONUserLocationLocation struct {
	Building      *string `json:"building,omitempty"`
	DateTime      *string `json:"date_time,omitempty"`
	DateTimeEpoch *string `json:"date_time_epoch,omitempty"`
	DateTimeUtc   *string `json:"date_time_utc,omitempty"`
	Department    *string `json:"department,omitempty"`
	EmailAddress  *string `json:"email_address,omitempty"`
	FullName      *string `json:"full_name,omitempty"`
	PhoneNumber   *string `json:"phone_number,omitempty"`
	Position      *string `json:"position,omitempty"`
	Room          *string `json:"room,omitempty"`
	Username      *string `json:"username,omitempty"`
}

type FindComputerHistoryByName200ApplicationJSONUserLocation struct {
	Location *FindComputerHistoryByName200ApplicationJSONUserLocationLocation `json:"location,omitempty"`
}

// FindComputerHistoryByName200ApplicationJSON - OK
type FindComputerHistoryByName200ApplicationJSON struct {
	Audits                  []FindComputerHistoryByName200ApplicationJSONAudits                 `json:"audits,omitempty"`
	CasperImagingLogs       []FindComputerHistoryByName200ApplicationJSONCasperImagingLogs      `json:"casper_imaging_logs,omitempty"`
	CasperRemoteLogs        []FindComputerHistoryByName200ApplicationJSONCasperRemoteLogs       `json:"casper_remote_logs,omitempty"`
	Commands                *FindComputerHistoryByName200ApplicationJSONCommands                `json:"commands,omitempty"`
	ComputerUsageLogs       []FindComputerHistoryByName200ApplicationJSONComputerUsageLogs      `json:"computer_usage_logs,omitempty"`
	General                 *FindComputerHistoryByName200ApplicationJSONGeneral                 `json:"general,omitempty"`
	MacAppStoreApplications *FindComputerHistoryByName200ApplicationJSONMacAppStoreApplications `json:"mac_app_store_applications,omitempty"`
	PolicyLogs              []FindComputerHistoryByName200ApplicationJSONPolicyLogs             `json:"policy_logs,omitempty"`
	ScreenSharingLogs       []FindComputerHistoryByName200ApplicationJSONScreenSharingLogs      `json:"screen_sharing_logs,omitempty"`
	UserLocation            []FindComputerHistoryByName200ApplicationJSONUserLocation           `json:"user_location,omitempty"`
}

type FindComputerHistoryByNameResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	FindComputerHistoryByName200ApplicationJSONObject *FindComputerHistoryByName200ApplicationJSON
}
