// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// FindManagedPreferenceProfilesByNameSubsetSubset - Subset to filter by
type FindManagedPreferenceProfilesByNameSubsetSubset string

const (
	FindManagedPreferenceProfilesByNameSubsetSubsetGeneral  FindManagedPreferenceProfilesByNameSubsetSubset = "General"
	FindManagedPreferenceProfilesByNameSubsetSubsetScope    FindManagedPreferenceProfilesByNameSubsetSubset = "Scope"
	FindManagedPreferenceProfilesByNameSubsetSubsetSettings FindManagedPreferenceProfilesByNameSubsetSubset = "Settings"
)

func (e FindManagedPreferenceProfilesByNameSubsetSubset) ToPointer() *FindManagedPreferenceProfilesByNameSubsetSubset {
	return &e
}

func (e *FindManagedPreferenceProfilesByNameSubsetSubset) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "General":
		fallthrough
	case "Scope":
		fallthrough
	case "Settings":
		*e = FindManagedPreferenceProfilesByNameSubsetSubset(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FindManagedPreferenceProfilesByNameSubsetSubset: %v", v)
	}
}

type FindManagedPreferenceProfilesByNameSubsetRequest struct {
	// Name to filter by
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Subset to filter by
	Subset FindManagedPreferenceProfilesByNameSubsetSubset `pathParam:"style=simple,explode=false,name=subset"`
}

type FindManagedPreferenceProfilesByNameSubset200ApplicationXMLGeneral struct {
	Enabled *bool
	ID      *int64
	Name    string
	Plist   *string
}

// FindManagedPreferenceProfilesByNameSubset200ApplicationXML - OK
type FindManagedPreferenceProfilesByNameSubset200ApplicationXML struct {
	General *FindManagedPreferenceProfilesByNameSubset200ApplicationXMLGeneral
}

type FindManagedPreferenceProfilesByNameSubset200ApplicationJSONGeneral struct {
	Enabled *bool   `json:"enabled,omitempty"`
	ID      *int64  `json:"id,omitempty"`
	Name    string  `json:"name"`
	Plist   *string `json:"plist,omitempty"`
}

// FindManagedPreferenceProfilesByNameSubset200ApplicationJSON - OK
type FindManagedPreferenceProfilesByNameSubset200ApplicationJSON struct {
	General *FindManagedPreferenceProfilesByNameSubset200ApplicationJSONGeneral `json:"general,omitempty"`
}

type FindManagedPreferenceProfilesByNameSubsetResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	FindManagedPreferenceProfilesByNameSubset200ApplicationJSONObject *FindManagedPreferenceProfilesByNameSubset200ApplicationJSON
}
