// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PatchsoftwaretitlesIDByIDDeleteRequest struct {
	// ID value to update by
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type PatchsoftwaretitlesIDByIDDeleteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
