// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateMobileDeviceProvisioningProfilesByIDRequest struct {
	// Id value to filter by
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateMobileDeviceProvisioningProfilesByID200ApplicationXMLGeneral struct {
	DisplayName *string
	ID          *int64
	Name        *string
	UUID        *string
}

// UpdateMobileDeviceProvisioningProfilesByID200ApplicationXML - OK
type UpdateMobileDeviceProvisioningProfilesByID200ApplicationXML struct {
	General *UpdateMobileDeviceProvisioningProfilesByID200ApplicationXMLGeneral
}

type UpdateMobileDeviceProvisioningProfilesByID200ApplicationJSONGeneral struct {
	DisplayName *string `json:"display_name,omitempty"`
	ID          *int64  `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	UUID        *string `json:"uuid,omitempty"`
}

// UpdateMobileDeviceProvisioningProfilesByID200ApplicationJSON - OK
type UpdateMobileDeviceProvisioningProfilesByID200ApplicationJSON struct {
	General *UpdateMobileDeviceProvisioningProfilesByID200ApplicationJSONGeneral `json:"general,omitempty"`
}

type UpdateMobileDeviceProvisioningProfilesByIDResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	UpdateMobileDeviceProvisioningProfilesByID200ApplicationJSONObject *UpdateMobileDeviceProvisioningProfilesByID200ApplicationJSON
}
