// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateMobileDeviceByMacAddressRequest struct {
	// Mac address value to filter by
	Macaddress string `pathParam:"style=simple,explode=false,name=macaddress"`
}

type UpdateMobileDeviceByMacAddressResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
